import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { css, cx } from '@/styled-system/css';

import { ColorModeProvider } from '../components/ColorModeProvider';
import { Sidebar } from './ui/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const mainStack = css({
  maxW: 'breakpoint-2xl',
  w: 'full',
  h: 'full',
  display: 'grid',
  gridTemplateColumns: {
    base: '1fr',
    md: '1fr 300px',
    lg: '1fr 320px'
  },
  gap: 2,
  px: 2
});

const header = css({
  maxW: 'full',
  height: '16',
  background: 'primaryForeground'
});

const footer = css({
  maxW: 'full',
  height: 'auto',
  background: 'secondaryForeground'
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja' data-color-mode='light'>
      <body
        className={cx(
          css({ backgroundColor: 'background', height: '100svh' }),
          inter.className
        )}
      >
        <ColorModeProvider>
          <header className={header}>header</header>
          <div className={mainStack}>
            {children}
            <Sidebar />
          </div>
          <footer className={footer}>footer</footer>
        </ColorModeProvider>
      </body>
    </html>
  );
}
