import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { css, cx } from '@/styled-system/css';

import { ColorModeProvider } from '../components/ColorModeProvider';
import { Sidebar } from './ui/sidebar';
import { ColorModeToggle } from '@/components/ColorModeToggle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const container = css({
  position: 'relative',
  maxW: 'full',
  w: 'full',
  h: 'full',
  display: 'grid',
  gridTemplateColumns: '1fr',
  gridTemplateRows: '70px 1fr 320px',
  justifyContent: 'center',
  justifyItems: 'center',
  gap: 2
});

const mainStack = css({
  maxW: 'breakpoint-2xl',
  maxH: 'full',
  w: 'full',
  h: 'full',
  display: 'grid',
  gridTemplateColumns: {
    base: '1fr',
    md: '1fr 300px',
    lg: '1fr 320px'
  },
  gap: 2,
  px: 2
});

const header = css({
  maxW: 'full',
  w: 'full',
  h: 'full',
  background: 'foreground',
  position: 'sticky',
  left: 0,
  top: 0
});

const footer = css({
  maxW: 'full',
  w: 'full',
  height: 'auto',
  background: 'gray.900'
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja' data-color-mode='light'>
      <body
        className={cx(
          css({ backgroundColor: 'background', height: '100svh' }),
          inter.className
        )}
      >
        <ColorModeProvider>
          <div className={container}>
            <header className={header}>
              <ColorModeToggle />
            </header>
            <div className={mainStack}>
              {children}
              <Sidebar />
            </div>
            <footer className={footer}>footer</footer>
          </div>
        </ColorModeProvider>
      </body>
    </html>
  );
}
