import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { css, cx } from '@/styled-system/css'

import { ColorModeProvider } from './components/ColorModeProvider'
import { ColorModeToggle } from './components/ColorModeToggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja' data-color-mode='light'>
      <body className={cx(css({ backgroundColor: 'background' }), inter.className)}>
        <ColorModeProvider>
          <ColorModeToggle />
          {children}
        </ColorModeProvider>
      </body>
    </html>
  )
}
